name: Upstream Sync

on:
  schedule:
    - cron: "0 3 * * 0"  
  workflow_dispatch: {}  

permissions:
  contents: write        

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync fork from upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          with:
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

          upstream_sync_repo: kamranahmedse/developer-roadmap
          upstream_sync_branch: master
